# Generated by Django 5.1.6 on 2025-02-21 20:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=accounts.models.generate_unique_username, max_length=150, unique=True),
        ),
    ]
