# Generated by Django 5.1.6 on 2025-02-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='category',
            field=models.CharField(choices=[('ANIMALS', 'Homeless Animals'), ('CHARITY', 'Charity'), ('ECOSYSTEM', 'Ecosystem'), ('MEDICAL', 'Medical Help'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.RemoveField(
            model_name='donation',
            name='message',
        ),
        migrations.DeleteModel(
            name='DonationCategory',
        ),
    ]
